# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                id = 56,
                platform = '',
                union_id = '',
                nick_name = '',
                avatar = '',
                data = '',
                user_name = '',
                pwd = '',
                email = '',
                email_is_valid = True,
                phone = '',
                phone_is_valid = True,
                relation_chain = '',
                interest_tags = '',
                biography = '',
                gender = '',
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                occupation = '',
                education = '',
                contact = '',
                languages = '',
                social_links = '',
                relationship_status = '',
                company = '',
                industry = '',
                company_position = '',
                private_settings = '',
                is_lock = True,
                lock_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enable_user_name_sign_in = True,
                enable_email_sign_in = True,
                enable_phone_sign_in = True,
                enable_union_id_sign_in = True,
                enable_o_auth = True,
                enable2_fa_auth = True,
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_update = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return User(
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
