# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.phone_sign_in_request import PhoneSignInRequest

class TestPhoneSignInRequest(unittest.TestCase):
    """PhoneSignInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneSignInRequest:
        """Test PhoneSignInRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneSignInRequest`
        """
        model = PhoneSignInRequest()
        if include_optional:
            return PhoneSignInRequest(
                phone = '0',
                verify_code = '0',
                two_factor_code = ''
            )
        else:
            return PhoneSignInRequest(
                phone = '0',
                verify_code = '0',
        )
        """

    def testPhoneSignInRequest(self):
        """Test PhoneSignInRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
