# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.currency import Currency

class TestCurrency(unittest.TestCase):
    """Currency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Currency:
        """Test Currency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Currency`
        """
        model = Currency()
        if include_optional:
            return Currency(
                id = 56,
                name = '',
                code = '',
                symbol = '',
                issuer = '',
                currency_type = '',
                tags = '',
                status = True,
                enable_virtual_recharge = True,
                enable_virtual_consume = True,
                description = '',
                fiat_exchange_rate = 56,
                fiat_daily_recharge_limit = 56,
                total_supply = 56,
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_update = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Currency(
        )
        """

    def testCurrency(self):
        """Test Currency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
