# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.user_currency_api import UserCurrencyApi


class TestUserCurrencyApi(unittest.TestCase):
    """UserCurrencyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserCurrencyApi()

    def tearDown(self) -> None:
        pass

    def test_user_currencies(self) -> None:
        """Test case for user_currencies

        资产
        """
        pass

    def test_user_currency_consume(self) -> None:
        """Test case for user_currency_consume

        消费虚拟币
        """
        pass

    def test_user_currency_exchange(self) -> None:
        """Test case for user_currency_exchange

        兑换虚拟币
        """
        pass

    def test_user_currency_recharge(self) -> None:
        """Test case for user_currency_recharge

        充值虚拟币
        """
        pass

    def test_user_currency_transactions(self) -> None:
        """Test case for user_currency_transactions

        虚拟币交易记录
        """
        pass


if __name__ == '__main__':
    unittest.main()
