# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.grant_request import GrantRequest

class TestGrantRequest(unittest.TestCase):
    """GrantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantRequest:
        """Test GrantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantRequest`
        """
        model = GrantRequest()
        if include_optional:
            return GrantRequest(
                redirect_uri = '',
                grant_type = 'unionid0',
                scopes = '0',
                user_name = '',
                password = '',
                union_id = '',
                platform = '',
                expire_in_days = 1
            )
        else:
            return GrantRequest(
                grant_type = 'unionid0',
                scopes = '0',
        )
        """

    def testGrantRequest(self):
        """Test GrantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
