# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.follower_put_model import FollowerPutModel

class TestFollowerPutModel(unittest.TestCase):
    """FollowerPutModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FollowerPutModel:
        """Test FollowerPutModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FollowerPutModel`
        """
        model = FollowerPutModel()
        if include_optional:
            return FollowerPutModel(
                alias = '',
                closeness_score = 56,
                attention_score = 56,
                tags = '',
                status = '',
                remark = ''
            )
        else:
            return FollowerPutModel(
        )
        """

    def testFollowerPutModel(self):
        """Test FollowerPutModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
