# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.return_page_notify_request import ReturnPageNotifyRequest

class TestReturnPageNotifyRequest(unittest.TestCase):
    """ReturnPageNotifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnPageNotifyRequest:
        """Test ReturnPageNotifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnPageNotifyRequest`
        """
        model = ReturnPageNotifyRequest()
        if include_optional:
            return ReturnPageNotifyRequest(
                app_id = '',
                auth_app_id = '',
                charset = '',
                method = '',
                out_trade_no = '',
                seller_id = '',
                sign = '',
                sign_type = '',
                timestamp = '',
                total_amount = '',
                trade_no = '',
                version = ''
            )
        else:
            return ReturnPageNotifyRequest(
        )
        """

    def testReturnPageNotifyRequest(self):
        """Test ReturnPageNotifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
