# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.team_api import TeamApi


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamApi()

    def tearDown(self) -> None:
        pass

    def test_team_delete(self) -> None:
        """Test case for team_delete

        删除团队
        """
        pass

    def test_team_post(self) -> None:
        """Test case for team_post

        创建团队
        """
        pass

    def test_team_put(self) -> None:
        """Test case for team_put

        更新团队
        """
        pass

    def test_teams(self) -> None:
        """Test case for teams

        团队列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
