# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.sign_up_request import SignUpRequest

class TestSignUpRequest(unittest.TestCase):
    """SignUpRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignUpRequest:
        """Test SignUpRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignUpRequest`
        """
        model = SignUpRequest()
        if include_optional:
            return SignUpRequest(
                user_name = '0',
                pwd = '012345',
                nick_name = '',
                avatar = '',
                data = '',
                email = 'A@9LCSLv1C1ylmgd0.Y2TA5TkIRHRRA401iz1CiIy.dNTRd',
                email_code = '4807',
                phone = '48072888001',
                phone_code = '4807'
            )
        else:
            return SignUpRequest(
                user_name = '0',
                pwd = '012345',
        )
        """

    def testSignUpRequest(self):
        """Test SignUpRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
