# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.update_profile_request import UpdateProfileRequest

class TestUpdateProfileRequest(unittest.TestCase):
    """UpdateProfileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProfileRequest:
        """Test UpdateProfileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProfileRequest`
        """
        model = UpdateProfileRequest()
        if include_optional:
            return UpdateProfileRequest(
                avatar = '',
                data = '',
                nick_name = '',
                interest_tags = '',
                biography = '',
                gender = '',
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                occupation = '',
                education = '',
                contact = '',
                languages = '',
                social_links = '',
                relationship_status = '',
                company = '',
                industry = '',
                company_position = '',
                private_settings = ''
            )
        else:
            return UpdateProfileRequest(
        )
        """

    def testUpdateProfileRequest(self):
        """Test UpdateProfileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
