# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.authorize_policy_api import AuthorizePolicyApi


class TestAuthorizePolicyApi(unittest.TestCase):
    """AuthorizePolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthorizePolicyApi()

    def tearDown(self) -> None:
        pass

    def test_authorize_policies(self) -> None:
        """Test case for authorize_policies

        鉴权列表
        """
        pass

    def test_authorize_policy(self) -> None:
        """Test case for authorize_policy

        鉴权详情
        """
        pass

    def test_authorize_policy_delete(self) -> None:
        """Test case for authorize_policy_delete

        删除鉴权策略
        """
        pass

    def test_authorize_policy_post(self) -> None:
        """Test case for authorize_policy_post

        添加鉴权策略
        """
        pass

    def test_authorize_policy_put(self) -> None:
        """Test case for authorize_policy_put

        更新鉴权策略
        """
        pass


if __name__ == '__main__':
    unittest.main()
