# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.post_index_request import PostIndexRequest

class TestPostIndexRequest(unittest.TestCase):
    """PostIndexRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostIndexRequest:
        """Test PostIndexRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostIndexRequest`
        """
        model = PostIndexRequest()
        if include_optional:
            return PostIndexRequest(
                model = {
                    'key' : [
                        null
                        ]
                    },
                options = {
                    'key' : [
                        null
                        ]
                    }
            )
        else:
            return PostIndexRequest(
                model = {
                    'key' : [
                        null
                        ]
                    },
        )
        """

    def testPostIndexRequest(self):
        """Test PostIndexRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
