# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.access_token_api import AccessTokenApi


class TestAccessTokenApi(unittest.TestCase):
    """AccessTokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessTokenApi()

    def tearDown(self) -> None:
        pass

    def test_access_token_delete(self) -> None:
        """Test case for access_token_delete

        删除令牌
        """
        pass

    def test_access_token_post(self) -> None:
        """Test case for access_token_post

        创建令牌
        """
        pass

    def test_access_token_put(self) -> None:
        """Test case for access_token_put

        更新令牌
        """
        pass

    def test_access_tokens(self) -> None:
        """Test case for access_tokens

        令牌列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
