# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_user(self) -> None:
        """Test case for user

        用户详情
        """
        pass

    def test_user_clear(self) -> None:
        """Test case for user_clear

        清空用户数据
        """
        pass

    def test_user_common_interests(self) -> None:
        """Test case for user_common_interests

        有共同爱好的用户推荐
        """
        pass

    def test_user_delete(self) -> None:
        """Test case for user_delete

        删除用户
        """
        pass

    def test_user_email_sign_in(self) -> None:
        """Test case for user_email_sign_in

        邮箱登录
        """
        pass

    def test_user_email_sign_up(self) -> None:
        """Test case for user_email_sign_up

        邮箱注册
        """
        pass

    def test_user_export(self) -> None:
        """Test case for user_export

        导出用户数据
        """
        pass

    def test_user_follow_user(self) -> None:
        """Test case for user_follow_user

        关注用户
        """
        pass

    def test_user_follower_put(self) -> None:
        """Test case for user_follower_put

        更新粉丝
        """
        pass

    def test_user_followers(self) -> None:
        """Test case for user_followers

        我的粉丝
        """
        pass

    def test_user_following(self) -> None:
        """Test case for user_following

        我的关注
        """
        pass

    def test_user_friends_near_by(self) -> None:
        """Test case for user_friends_near_by

        附近的用户推荐
        """
        pass

    def test_user_import(self) -> None:
        """Test case for user_import

        导入用户数据
        """
        pass

    def test_user_location(self) -> None:
        """Test case for user_location

        位置详情
        """
        pass

    def test_user_location_delete(self) -> None:
        """Test case for user_location_delete

        删除位置
        """
        pass

    def test_user_location_post(self) -> None:
        """Test case for user_location_post

        添加位置
        """
        pass

    def test_user_location_put(self) -> None:
        """Test case for user_location_put

        更新位置
        """
        pass

    def test_user_locations(self) -> None:
        """Test case for user_locations

        位置列表
        """
        pass

    def test_user_mutual_followers(self) -> None:
        """Test case for user_mutual_followers

        有共同粉丝的用户推荐
        """
        pass

    def test_user_mutual_followings(self) -> None:
        """Test case for user_mutual_followings

        有共同关注的用户推荐
        """
        pass

    def test_user_o_auth_account_bind(self) -> None:
        """Test case for user_o_auth_account_bind

        外部账号 绑定
        """
        pass

    def test_user_o_auth_account_sign_in(self) -> None:
        """Test case for user_o_auth_account_sign_in

        外部账号 登录
        """
        pass

    def test_user_o_auth_accounts(self) -> None:
        """Test case for user_o_auth_accounts

        外部账号 绑定列表
        """
        pass

    def test_user_o_auth_accounts_put_bind(self) -> None:
        """Test case for user_o_auth_accounts_put_bind

        外部账号 更新绑定
        """
        pass

    def test_user_o_auth_accounts_un_bind(self) -> None:
        """Test case for user_o_auth_accounts_un_bind

        外部账号 删除绑定
        """
        pass

    def test_user_phone_sign_in(self) -> None:
        """Test case for user_phone_sign_in

        手机登录
        """
        pass

    def test_user_phone_sign_up(self) -> None:
        """Test case for user_phone_sign_up

        手机注册
        """
        pass

    def test_user_profile(self) -> None:
        """Test case for user_profile

        获取个人资料
        """
        pass

    def test_user_put(self) -> None:
        """Test case for user_put

        更新用户
        """
        pass

    def test_user_qr_code_pre_sign_in(self) -> None:
        """Test case for user_qr_code_pre_sign_in

        微信小程序 - 预登陆
        """
        pass

    def test_user_qr_code_scan(self) -> None:
        """Test case for user_qr_code_scan

        微信小程序 - 扫码
        """
        pass

    def test_user_qr_code_sign_in(self) -> None:
        """Test case for user_qr_code_sign_in

        微信小程序 - 网页登录
        """
        pass

    def test_user_qr_code_sign_up(self) -> None:
        """Test case for user_qr_code_sign_up

        微信小程序 - 注册
        """
        pass

    def test_user_reset_pwd(self) -> None:
        """Test case for user_reset_pwd

        重置密码
        """
        pass

    def test_user_send_email_code(self) -> None:
        """Test case for user_send_email_code

        发送邮箱验证码
        """
        pass

    def test_user_send_sms_code(self) -> None:
        """Test case for user_send_sms_code

        发送手机验证码
        """
        pass

    def test_user_sign_in(self) -> None:
        """Test case for user_sign_in

        账号密码 登录
        """
        pass

    def test_user_sign_up(self) -> None:
        """Test case for user_sign_up

        账号密码 注册
        """
        pass

    def test_user_two_factor_auth(self) -> None:
        """Test case for user_two_factor_auth

        双因素验证
        """
        pass

    def test_user_unfollow_user(self) -> None:
        """Test case for user_unfollow_user

        取消关注
        """
        pass

    def test_user_union_id_sign_in(self) -> None:
        """Test case for user_union_id_sign_in

        UnionID登录
        """
        pass

    def test_user_union_id_sign_up(self) -> None:
        """Test case for user_union_id_sign_up

        UnionID注册
        """
        pass

    def test_user_update_profile(self) -> None:
        """Test case for user_update_profile

        更新个人资料
        """
        pass

    def test_users(self) -> None:
        """Test case for users

        用户列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
