# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.send_sms_code_request import SendSMSCodeRequest

class TestSendSMSCodeRequest(unittest.TestCase):
    """SendSMSCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendSMSCodeRequest:
        """Test SendSMSCodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendSMSCodeRequest`
        """
        model = SendSMSCodeRequest()
        if include_optional:
            return SendSMSCodeRequest(
                phone = '0',
                type = '0'
            )
        else:
            return SendSMSCodeRequest(
                phone = '0',
                type = '0',
        )
        """

    def testSendSMSCodeRequest(self):
        """Test SendSMSCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
