# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.qr_code_sign_up_request import QRCodeSignUpRequest

class TestQRCodeSignUpRequest(unittest.TestCase):
    """QRCodeSignUpRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QRCodeSignUpRequest:
        """Test QRCodeSignUpRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QRCodeSignUpRequest`
        """
        model = QRCodeSignUpRequest()
        if include_optional:
            return QRCodeSignUpRequest(
                sign_in_key = 56,
                union_id = '0',
                nick_name = '',
                avatar = '',
                data = '',
                email = 'A@9LCSLv1C1ylmgd0.Y2TA5TkIRHRRA401iz1CiIy.dNTRd',
                email_code = '4807',
                phone = '48072888001',
                phone_code = '4807'
            )
        else:
            return QRCodeSignUpRequest(
                union_id = '0',
        )
        """

    def testQRCodeSignUpRequest(self):
        """Test QRCodeSignUpRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
