# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.service_item import ServiceItem

class TestServiceItem(unittest.TestCase):
    """ServiceItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceItem:
        """Test ServiceItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceItem`
        """
        model = ServiceItem()
        if include_optional:
            return ServiceItem(
                id = 56,
                biz_code = '',
                provider_code = '',
                group_code = '',
                name = '',
                code = '',
                value_type = '',
                icon = '',
                value_defaults = '',
                description = '',
                tags = '',
                is_system = True,
                show = True,
                show_index = 56,
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_update = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ServiceItem(
        )
        """

    def testServiceItem(self):
        """Test ServiceItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
