# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.alipay_api import AlipayApi


class TestAlipayApi(unittest.TestCase):
    """AlipayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlipayApi()

    def tearDown(self) -> None:
        pass

    def test_alipay_create_order(self) -> None:
        """Test case for alipay_create_order

        创建订单 - 当面付
        """
        pass

    def test_alipay_create_order_page_pay(self) -> None:
        """Test case for alipay_create_order_page_pay

        创建订单 - PC支付
        """
        pass

    def test_alipay_create_order_wap_pay(self) -> None:
        """Test case for alipay_create_order_wap_pay

        创建订单 - WAP支付
        """
        pass

    def test_alipay_order_detail(self) -> None:
        """Test case for alipay_order_detail

        订单详情
        """
        pass

    def test_alipay_order_refund(self) -> None:
        """Test case for alipay_order_refund

        订单退款
        """
        pass

    def test_alipay_return_page_notify(self) -> None:
        """Test case for alipay_return_page_notify

        支付成功同步通知
        """
        pass


if __name__ == '__main__':
    unittest.main()
