# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_project(self) -> None:
        """Test case for project

        项目详情
        """
        pass

    def test_project_delete(self) -> None:
        """Test case for project_delete

        删除项目
        """
        pass

    def test_project_post(self) -> None:
        """Test case for project_post

        创建项目
        """
        pass

    def test_project_put(self) -> None:
        """Test case for project_put

        更新项目
        """
        pass

    def test_projects(self) -> None:
        """Test case for projects

        项目列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
