# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.app_user_reset_pwd_request import AppUserResetPwdRequest

class TestAppUserResetPwdRequest(unittest.TestCase):
    """AppUserResetPwdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppUserResetPwdRequest:
        """Test AppUserResetPwdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppUserResetPwdRequest`
        """
        model = AppUserResetPwdRequest()
        if include_optional:
            return AppUserResetPwdRequest(
                phone = '',
                email = '',
                code = '48070',
                pwd = 'jUR,rZ#UM/?R,Fp^l6$A0'
            )
        else:
            return AppUserResetPwdRequest(
                code = '48070',
                pwd = 'jUR,rZ#UM/?R,Fp^l6$A0',
        )
        """

    def testAppUserResetPwdRequest(self):
        """Test AppUserResetPwdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
