# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.o_auth_account_sign_in_request import OAuthAccountSignInRequest

class TestOAuthAccountSignInRequest(unittest.TestCase):
    """OAuthAccountSignInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuthAccountSignInRequest:
        """Test OAuthAccountSignInRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuthAccountSignInRequest`
        """
        model = OAuthAccountSignInRequest()
        if include_optional:
            return OAuthAccountSignInRequest(
                union_id = '0',
                platform = '0',
                two_factor_code = ''
            )
        else:
            return OAuthAccountSignInRequest(
                union_id = '0',
                platform = '0',
        )
        """

    def testOAuthAccountSignInRequest(self):
        """Test OAuthAccountSignInRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
