# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.app_api import AppApi


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppApi()

    def tearDown(self) -> None:
        pass

    def test_app(self) -> None:
        """Test case for app

        应用详情
        """
        pass

    def test_app2_fa(self) -> None:
        """Test case for app2_fa

        双因素验证 获取
        """
        pass

    def test_app2_fa_check(self) -> None:
        """Test case for app2_fa_check

        双因素验证 验证
        """
        pass

    def test_app_check_version(self) -> None:
        """Test case for app_check_version

        更新应用数据库
        """
        pass

    def test_app_delete(self) -> None:
        """Test case for app_delete

        删除应用
        """
        pass

    def test_app_info(self) -> None:
        """Test case for app_info

        应用详情
        """
        pass

    def test_app_post(self) -> None:
        """Test case for app_post

        创建应用
        """
        pass

    def test_app_put(self) -> None:
        """Test case for app_put

        更新应用
        """
        pass

    def test_app_transfer(self) -> None:
        """Test case for app_transfer

        转移应用
        """
        pass

    def test_apps(self) -> None:
        """Test case for apps

        应用列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
