# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.wechat_api import WechatApi


class TestWechatApi(unittest.TestCase):
    """WechatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WechatApi()

    def tearDown(self) -> None:
        pass

    def test_wechat_decrypt(self) -> None:
        """Test case for wechat_decrypt

        小程序-解密数据
        """
        pass

    def test_wechat_generate_scheme(self) -> None:
        """Test case for wechat_generate_scheme

        小程序-生成scheme码(该接口用于获取小程序 scheme 码，适用于短信、邮件、外部网页、微信内等拉起小程序的业务场景)
        """
        pass

    def test_wechat_js_code2_session(self) -> None:
        """Test case for wechat_js_code2_session

        小程序-登录凭证校验
        """
        pass

    def test_wechat_js_config(self) -> None:
        """Test case for wechat_js_config

        公众号H5-JS SDK Config
        """
        pass

    def test_wechat_subscribe_msg(self) -> None:
        """Test case for wechat_subscribe_msg

        公众号H5-发送一次性订阅消息
        """
        pass

    def test_wechat_subscribe_send(self) -> None:
        """Test case for wechat_subscribe_send

        小程序-发送订阅消息
        """
        pass

    def test_wechat_url_link_generate(self) -> None:
        """Test case for wechat_url_link_generate

        小程序-生成网页跳转地址(获取小程序 URL Link，适用于短信、邮件、网页、微信内等拉起小程序的业务场景)
        """
        pass

    def test_wechat_user_info(self) -> None:
        """Test case for wechat_user_info

        公众号H5-获取用户UnionID
        """
        pass

    def test_wechat_wxa_code_get(self) -> None:
        """Test case for wechat_wxa_code_get

        小程序-获取小程序码
        """
        pass

    def test_wechat_wxa_code_get_unlimited(self) -> None:
        """Test case for wechat_wxa_code_get_unlimited

        小程序-获取小程序码(无限制)
        """
        pass


if __name__ == '__main__':
    unittest.main()
