# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.qr_code_pre_sign_in_request import QRCodePreSignInRequest

class TestQRCodePreSignInRequest(unittest.TestCase):
    """QRCodePreSignInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QRCodePreSignInRequest:
        """Test QRCodePreSignInRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QRCodePreSignInRequest`
        """
        model = QRCodePreSignInRequest()
        if include_optional:
            return QRCodePreSignInRequest(
                scopes = '',
                remark = '',
                scheme = ''
            )
        else:
            return QRCodePreSignInRequest(
        )
        """

    def testQRCodePreSignInRequest(self):
        """Test QRCodePreSignInRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
