# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.tenant_api import TenantApi


class TestTenantApi(unittest.TestCase):
    """TenantApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantApi()

    def tearDown(self) -> None:
        pass

    def test_tenant(self) -> None:
        """Test case for tenant

        服务器详情
        """
        pass

    def test_tenant_backup(self) -> None:
        """Test case for tenant_backup

        备份数据库
        """
        pass

    def test_tenant_backup_delete(self) -> None:
        """Test case for tenant_backup_delete

        删除备份
        """
        pass

    def test_tenant_backup_remark(self) -> None:
        """Test case for tenant_backup_remark

        标注数据库备份
        """
        pass

    def test_tenant_backup_remark_put(self) -> None:
        """Test case for tenant_backup_remark_put

        更新数据库备份标注
        """
        pass

    def test_tenant_backups(self) -> None:
        """Test case for tenant_backups

        数据库备份列表
        """
        pass

    def test_tenant_check_version(self) -> None:
        """Test case for tenant_check_version

        升级数据库
        """
        pass

    def test_tenant_put(self) -> None:
        """Test case for tenant_put

        更新服务器
        """
        pass

    def test_tenant_rollback(self) -> None:
        """Test case for tenant_rollback

        回滚数据库
        """
        pass

    def test_tenant_settings(self) -> None:
        """Test case for tenant_settings

        配置列表
        """
        pass

    def test_tenants(self) -> None:
        """Test case for tenants

        服务器列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
