# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.currency_api import CurrencyApi


class TestCurrencyApi(unittest.TestCase):
    """CurrencyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrencyApi()

    def tearDown(self) -> None:
        pass

    def test_currencies(self) -> None:
        """Test case for currencies

        货币列表
        """
        pass

    def test_currency(self) -> None:
        """Test case for currency

        货币详情
        """
        pass

    def test_currency_delete(self) -> None:
        """Test case for currency_delete

        删除货币
        """
        pass

    def test_currency_exchange_rate_delete(self) -> None:
        """Test case for currency_exchange_rate_delete

        删除汇率
        """
        pass

    def test_currency_exchange_rate_put(self) -> None:
        """Test case for currency_exchange_rate_put

        更新汇率
        """
        pass

    def test_currency_exchange_rates(self) -> None:
        """Test case for currency_exchange_rates

        汇率列表
        """
        pass

    def test_currency_post(self) -> None:
        """Test case for currency_post

        创建货币
        """
        pass

    def test_currency_put(self) -> None:
        """Test case for currency_put

        更新货币
        """
        pass

    def test_currency_transactions(self) -> None:
        """Test case for currency_transactions

        货币交易记录
        """
        pass


if __name__ == '__main__':
    unittest.main()
