# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.tenant_file_api import TenantFileApi


class TestTenantFileApi(unittest.TestCase):
    """TenantFileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantFileApi()

    def tearDown(self) -> None:
        pass

    def test_tenant_file_create_folder(self) -> None:
        """Test case for tenant_file_create_folder

        创建文件夹
        """
        pass

    def test_tenant_file_delete(self) -> None:
        """Test case for tenant_file_delete

        删除文件
        """
        pass

    def test_tenant_file_rename(self) -> None:
        """Test case for tenant_file_rename

        重命名文件
        """
        pass

    def test_tenant_file_upload(self) -> None:
        """Test case for tenant_file_upload

        上传文件
        """
        pass

    def test_tenant_files(self) -> None:
        """Test case for tenant_files

        文件列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
