# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.access_token_put_request import AccessTokenPutRequest

class TestAccessTokenPutRequest(unittest.TestCase):
    """AccessTokenPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessTokenPutRequest:
        """Test AccessTokenPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessTokenPutRequest`
        """
        model = AccessTokenPutRequest()
        if include_optional:
            return AccessTokenPutRequest(
                title = '0',
                tags = '',
                description = '',
                permissions = '',
                enable = True
            )
        else:
            return AccessTokenPutRequest(
                title = '0',
        )
        """

    def testAccessTokenPutRequest(self):
        """Test AccessTokenPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
