# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.o_auth_api import OAuthApi


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApi()

    def tearDown(self) -> None:
        pass

    def test_o_auth_authorize(self) -> None:
        """Test case for o_auth_authorize

        获取access_token
        """
        pass

    def test_o_auth_consents(self) -> None:
        """Test case for o_auth_consents

        授权记录
        """
        pass

    def test_o_auth_delete_consent(self) -> None:
        """Test case for o_auth_delete_consent

        删除授权记录
        """
        pass

    def test_o_auth_grant_code(self) -> None:
        """Test case for o_auth_grant_code

        申请授权码
        """
        pass

    def test_o_auth_profile(self) -> None:
        """Test case for o_auth_profile

        获取个人资料
        """
        pass


if __name__ == '__main__':
    unittest.main()
