# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.create_order_request import CreateOrderRequest

class TestCreateOrderRequest(unittest.TestCase):
    """CreateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrderRequest:
        """Test CreateOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderRequest`
        """
        model = CreateOrderRequest()
        if include_optional:
            return CreateOrderRequest(
                amount = 0.01,
                product_name = '0',
                product_type = '0',
                product_id = '0'
            )
        else:
            return CreateOrderRequest(
                amount = 0.01,
                product_name = '0',
                product_type = '0',
                product_id = '0',
        )
        """

    def testCreateOrderRequest(self):
        """Test CreateOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
