# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.user_setting_api import UserSettingApi


class TestUserSettingApi(unittest.TestCase):
    """UserSettingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserSettingApi()

    def tearDown(self) -> None:
        pass

    def test_user_setting(self) -> None:
        """Test case for user_setting

        用户配置项详情
        """
        pass

    def test_user_setting_delete(self) -> None:
        """Test case for user_setting_delete

        删除用户配置项
        """
        pass

    def test_user_setting_post(self) -> None:
        """Test case for user_setting_post

        添加用户配置项
        """
        pass

    def test_user_setting_put(self) -> None:
        """Test case for user_setting_put

        更新用户配置项
        """
        pass

    def test_user_settings(self) -> None:
        """Test case for user_settings

        用户配置列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
