# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.models.alipay_create_order_page_pay_request import AlipayCreateOrderPagePayRequest

class TestAlipayCreateOrderPagePayRequest(unittest.TestCase):
    """AlipayCreateOrderPagePayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlipayCreateOrderPagePayRequest:
        """Test AlipayCreateOrderPagePayRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlipayCreateOrderPagePayRequest`
        """
        model = AlipayCreateOrderPagePayRequest()
        if include_optional:
            return AlipayCreateOrderPagePayRequest(
                order_no = '0',
                amount = 0.01,
                subject = '0',
                return_url = ''
            )
        else:
            return AlipayCreateOrderPagePayRequest(
                order_no = '0',
                amount = 0.01,
                subject = '0',
        )
        """

    def testAlipayCreateOrderPagePayRequest(self):
        """Test AlipayCreateOrderPagePayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
