# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.ding_talk_api import DingTalkApi


class TestDingTalkApi(unittest.TestCase):
    """DingTalkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DingTalkApi()

    def tearDown(self) -> None:
        pass

    def test_ding_talk_user_info(self) -> None:
        """Test case for ding_talk_user_info

        获取用户资料
        """
        pass


if __name__ == '__main__':
    unittest.main()
