# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PMCore.Client.api.service_setting_api import ServiceSettingApi


class TestServiceSettingApi(unittest.TestCase):
    """ServiceSettingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceSettingApi()

    def tearDown(self) -> None:
        pass

    def test_service_setting(self) -> None:
        """Test case for service_setting

        配置详情
        """
        pass

    def test_service_setting_delete(self) -> None:
        """Test case for service_setting_delete

        删除配置
        """
        pass

    def test_service_setting_group(self) -> None:
        """Test case for service_setting_group

        服务分组详情
        """
        pass

    def test_service_setting_group_delete(self) -> None:
        """Test case for service_setting_group_delete

        删除服务分组
        """
        pass

    def test_service_setting_group_post(self) -> None:
        """Test case for service_setting_group_post

        添加服务分组
        """
        pass

    def test_service_setting_group_put(self) -> None:
        """Test case for service_setting_group_put

        更新服务分组
        """
        pass

    def test_service_setting_groups(self) -> None:
        """Test case for service_setting_groups

        服务分组
        """
        pass

    def test_service_setting_item(self) -> None:
        """Test case for service_setting_item

        服务配置详情
        """
        pass

    def test_service_setting_item_delete(self) -> None:
        """Test case for service_setting_item_delete

        删除服务配置
        """
        pass

    def test_service_setting_item_post(self) -> None:
        """Test case for service_setting_item_post

        添加服务配置
        """
        pass

    def test_service_setting_item_put(self) -> None:
        """Test case for service_setting_item_put

        更新服务配置
        """
        pass

    def test_service_setting_items(self) -> None:
        """Test case for service_setting_items

        服务配置列表
        """
        pass

    def test_service_setting_post(self) -> None:
        """Test case for service_setting_post

        增加配置
        """
        pass

    def test_service_setting_provider(self) -> None:
        """Test case for service_setting_provider

        服务商详情
        """
        pass

    def test_service_setting_provider_delete(self) -> None:
        """Test case for service_setting_provider_delete

        删除服务商
        """
        pass

    def test_service_setting_provider_post(self) -> None:
        """Test case for service_setting_provider_post

        添加服务商
        """
        pass

    def test_service_setting_provider_put(self) -> None:
        """Test case for service_setting_provider_put

        更新服务商
        """
        pass

    def test_service_setting_providers(self) -> None:
        """Test case for service_setting_providers

        服务商列表
        """
        pass

    def test_service_setting_put(self) -> None:
        """Test case for service_setting_put

        更新配置
        """
        pass

    def test_service_settings(self) -> None:
        """Test case for service_settings

        配置列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
